version: '3.8'

services:
  app:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bin-pomodoro
    hostname: pomodoro-server-hostname
    networks:
      - mynetwork
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://tulb:secret@pg4:5432/pomodoro?sslmode=disable
      - REDIS_CLIENT_ADDRESS=redis:6379
      - LOG_FILES_PATH=/app4/logs/
    volumes: 
      - ./logs:/app4/logs
  db:
    image: postgres
    container_name: postgrestulb4
    hostname: pg4
    networks:
      - mynetwork
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=tulb
      - POSTGRES_DB=pomodoro
      - PGDATA=/var/lib/postgresql/data/pgdata_tulb
    volumes:
      - pomoVol:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: rdbtulb2
    hostname: redis
    networks:
      - mynetwork
    ports:
      - 6379:6379
    volumes: 
      - pomoVol:/data

volumes:
  pomoVol: 

networks:
  mynetwork:
    driver: bridge
    